### ISSUE TITLE
Add build file for Github Action

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#18]
> [!IMPORTANT]
> Read issue #2 first

Create a file named `build.yml` in the path: `.github/workflows/`

The content of the file is as follows:

```yaml
name: Build Push/PR - Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node modules
        run: npm install --progress=false
      - name: Build project
        run: npm run build
```
