### ISSUE TITLE
Correct blank space - footer

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#7]
> [!IMPORTANT]
> Read issue #2 first

Add to the end of the file [src/styles.css](https://github.com/despensa-app/despensa-web/blob/cd28d939de45e19dac6203207c80aaf463a8110f/src/styles.css) the following code:

```css
.wrapper .content-wrapper {
  min-height: calc(100vh - calc(3.5rem + 1px));
}
``` 

To correct the blank space at the bottom of the page when navigating between pages.

![image](https://github.com/user-attachments/assets/c6aba00e-2936-4eda-9978-60a41c231fca)
